
title:        Systemcluster
email:        me@systemcluster.me
url:          "https://systemcluster.me" 
baseurl:      ""
logo:         "/img/avatar.jpg"

timezone: "Europe/Berlin"


markdown: kramdown
theme:    minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate


markdown:     kramdown
highlighter:  rouge


sidebar:
  - projects
  - articles
  - work
  - about


paginate:       8
paginate_path:  /articles/:num/
permalink:      /articles/:year/:month/:day/:title/

collections:
  work:
    output: false
    #permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:title
  

owner:
  name: Systemcluster
  avatar: "/img/chaika-med.png"
  gravatar: 
  job: "Software/Web/Game developer"
  bio: >
    Does freelance software work. 
    Writes games and open-source software as his pastime.
  email: me@systemcluster.me
  disqus-shortname: systemcluster #username
  twitter: #username
  facebook: #username
  google:
    plus:
    analytics: UA-104228705-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Systemcluster #username
  gitlab: Systemcluster
  bitbucket: Systemcluster
  stackoverflow: # 123456/username # from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  itchio: systemcluster
  keybase: systemcluster

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
